[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataLoaders = "2e981812-ef13-4a9c-bfa0-ab13047b12a9"
EvalMetrics = "251d5f9e-10c1-4699-ba24-e0ad168fa3e4"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
MLDataPattern = "9920b226-0b2a-5f5f-9153-9aa70a013f8b"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
MLBase = "f0e99cf1-93fa-52ec-9ecc-5026115318e0"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
ONNXNaiveNASflux = "2e935253-ba83-4645-9154-13ffeb13a688"
ONNXRunTime = "e034b28e-924e-41b2-b98f-d2bbeb830c6a"
OneHotArrays = "0b1bfda6-eb8a-41d2-88d8-f5af5cad476f"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
cuDNN = "02a925ec-e4fe-4b08-9a7e-0d78e3d38ccd"
